name: E2E Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: http://localhost:3000
          wait-on-timeout: 60
