name: E2E Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run ESLint check
        run: npx eslint src --ext .js,.jsx,.ts,.tsx --max-warnings 0

  cypress-run:
    runs-on: ubuntu-latest
    needs: lint
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run E2E Tests
        run: npm run test:e2e
