name: E2E Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run ESLint with fix
        id: eslint
        run: |
          npx eslint src --ext .js,.jsx,.ts,.tsx --fix --max-warnings 0 || echo "ESLINT_FAILED=true" >> $GITHUB_ENV

      - name: Commit changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "chore(lint): auto-fix lint errors via GitHub Actions"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Fail if lint issues remain
        if: env.ESLINT_FAILED == 'true'
        run: |
          echo "Lint errors could not be fixed automatically. Please fix them manually."
          exit 1

  cypress-run:
    runs-on: ubuntu-latest
    needs: lint
    if: success() # Rulează doar dacă lint a trecut
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test:e2e
