name: E2E Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite commit
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint with fix
        run: npx eslint src --ext .js,.jsx,.ts,.tsx --fix

      - name: Commit changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(lint): auto-fix lint errors via GitHub Actions"
            git push
          fi

  cypress-run:
    runs-on: ubuntu-latest
    needs: lint # Rulează doar dacă lint trece (inclusiv commitul, dacă e)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test:e2e
