name: E2E Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      # Pasul modificat: Rulează ESLint cu --fix fără a eșua imediat
      - name: Run ESLint and fix
        run: npx eslint src --ext .js,.jsx,.ts,.tsx --fix || true

      # Pasul modificat: Adaugă autentificare pentru git push
      - name: Commit changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore(lint): auto-fix lint errors via GitHub Actions"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes to commit."
          fi

      # Verificare finală pentru a asigura că nu există warn-uri rămase
      - name: Fail if any warnings remain
        run: npx eslint src --ext .js,.jsx,.ts,.tsx --max-warnings 0

  cypress-run:
    runs-on: ubuntu-latest
    needs: lint
    if: success() # Rulează doar dacă lint a trecut
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test:e2e
